sudo: false
language: elixir
git:
  depth: 3
elixir:
  - 1.3.2
  - 1.4.2
  - 1.5.2
otp_release:
  - 18.3
  - 19.0
  - 20.1

matrix:
  exclude:
    - elixir: 1.3.2
      otp_release: 20.1
    - elixir: 1.4.2
      otp_release: 20.1

env:
  - MIX_ENV=test
script:
  - mix test